<ul>
    <li><a href="index.php?road=voitures">Nos voitures</a></li>
    <?php if(isset($_SESSION['connected']) && $_SESSION['connected'] == true) : ?>
            <?php if(isset($_SESSION['user']) && $_SESSION['user']['role'] == "admin") : ?>
                <li><a href="index.php?road=displayFormAddVoiture">Ajouter une voiture</a></li>
                <li><a href="index.php?road=users">Liste des utilisateurs</a></li>
            <?php endif; ?>
        <li><a href="index.php?road=disconnect" class="active">Deconnexion</a></li>
    <?php else: ?>
        <li><a href="index.php?road=connect" class="active">Connexion</a></li>
        <li><a href="index.php?road=addUser" class="active">S'inscrire</a></li>
        
    <?php endif; ?>
    
</ul>
