<h1>Se connecter !</h1>

<form action="index.php?road=submitConnect" method="POST">
    <legend>Connexion</legend>

    <?php require_once('_errors.phtml');?>

    <label for="email">Entrez votre email</label>
    <input type="text" name="email" size="30" value="">

    <label for="password">Entrez votre mot de passe</label>
    <input type="password" name="password" size="30" id="password_1" style="width: 90%" value="">

    <input type="submit" value="Valider"/>
</form>