<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="LE FORUM DES MYTH CLOTH">
	<title><?= TITLEPAGE ?></title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="public/css/style.css">
</head>

<body>
	<header>
		<div class="container">
			<span>
				<a href="index.php?route=home" class="logo">
					<img src="public/img/<?= IMGLOGO ?>" alt="Logo">
					<strong><?= TITLEPAGE ?></strong>
				</a>
			</span>
			<nav>
				<div class="blocSearch">
					<input type="text" id="search" autocomplete="off" placeholder="Rechercher votre voiture !">
					<div id="targetLabels"></div>
				</div>
				<?php require_once('_identification.phtml');?>
			</nav>
		</div>
	</header>

	<main class="container">
		<nav>
			<?php require_once('_ulNav.phtml'); ?>
		</nav>

		<?php include $template ?>
	</main>

	<footer>
		
	</footer>

	<script src="public/js/script.js"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

</body>

</html>